name: CI for Node.js

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install and build 
        run: |
           defaults: 
            working-directory: ./testoapp
          npm install
           working-directory: ./testoapp 
          npm run build:prod
           working-directory: ./testoapp 
      - uses: actions/upload-artifact@master
        with: 
          name: build-result
          path: public/
     
  test:
    runs-on: ubuntu-latest
    needs: build
     
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with: 
        name: build-result
        path: public
  
    - name: Test with Node.js version ${{matrix.node-version}}    
      uses: actions/setup-node@v2.1.0 
      with:
        node-version: ${{matrix.node-version}}       
        
    - name: Install and test
      
      run: |
        defaults: 
          working-directory: ./testoapp
        npm install
           working-directory: ./testoapp   
        npm test: prod
           working-directory: ./testoapp   
            env:
              CI: true
 
