name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
      with:
        node-version: [10.x, 12.x, 14.x] 
     
    - run: npm ci
      working-directory: ./testoapp 
      
    - run: npm run deploy
      working-directory: ./testoapp   